package com.keepnc.data.auth

import androidx.annotation.Keep

/**
 * Holds the three values returned by Nextcloud Login Flow v2.
 *
 * [serverUrl]   — the Nextcloud server base URL (e.g. "https://cloud.example.com")
 * [loginName]   — the Nextcloud username
 * [appPassword] — a single-use app password generated by the server for this app;
 *                 NOT the user's main password
 */
@Keep
data class Credentials(
    val serverUrl: String,
    val loginName: String,
    val appPassword: String
)
